apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: my-first-tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
    app.kubernetes.io/part-of: tanzu-java-web-app
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/make0x0/my-first-tanzu-java-web-app/my-first-tanzu-java-web-app.git
